"""End-to-end browser flow for KitaBantu v2 (auth + role dashboards).
Run: python3 docs/flow-test.py  (needs: pip install playwright && python3 -m playwright install chromium)
Captures screenshots into docs/shots/ and fails on any console error."""
import json, os, sys, time
from playwright.sync_api import sync_playwright

BASE = os.environ.get('KB_BASE', 'http://localhost:3000')
OUT = os.path.join(os.path.dirname(__file__), 'shots')
os.makedirs(OUT, exist_ok=True)
errors = []
shots = []

def shot(page, name, full=False):
    path = os.path.join(OUT, f'{name}.png')
    page.screenshot(path=path, full_page=full)
    shots.append(path)
    print('  📸', name)

def login(page, email, pw='demo1234'):
    page.goto(BASE + '/')
    page.wait_for_selector('#auth:not(.hidden)')
    page.click(f'.acct[data-email="{email}"]')
    page.wait_for_selector('#app:not(.hidden)')
    page.wait_for_selector('.hero')
    page.wait_for_timeout(600)
    dismiss_perms(page)

def dismiss_perms(page):
    # v4: first login shows the permissions explainer; the flow test skips it (nav-test.py covers it)
    try:
        page.wait_for_selector('#permLater', timeout=2500)
        page.click('#permLater'); page.wait_for_timeout(300)
    except Exception:
        pass

def logout(page):
    page.evaluate("localStorage.removeItem('kb.token')")

with sync_playwright() as p:
    browser = p.chromium.launch()
    ctx = browser.new_context(viewport={'width': 1280, 'height': 860}, device_scale_factor=1)
    page = ctx.new_page()
    page.on('console', lambda m: errors.append(m.text) if m.type == 'error' else None)
    page.on('pageerror', lambda e: errors.append(str(e)))
    page.request.post(BASE + '/api/demo/reset')

    print('1. landing')
    page.goto(BASE + '/')
    page.wait_for_selector('.role-cards')
    page.wait_for_timeout(700)
    shot(page, '01-landing', full=True)

    print('2. sign up as a new helper')
    page.click('#pickHelper')
    page.click('#landGo')
    page.wait_for_selector('#suForm')
    shot(page, '02-signup-helper')
    page.fill('#sName', 'Judge Demo')
    page.fill('#sEmail', f'judge{int(time.time())}@test.my')
    page.fill('#sPass', 'secret12')
    page.fill('#sArea', 'Brickfields')
    page.click('#suForm button[type=submit]')
    page.wait_for_selector('#create')
    # <AvatarBuilder /> (Open Peeps layers from assetsManifest.json)
    page.wait_for_selector('#builderHost .ab .ab-tile')
    page.click('#builderHost .ab-grid .ab-tile:not(.locked)[data-id="head/bun"]')
    page.click('#builderHost .ab-tabs button:text-is("Glasses")')
    page.click('#builderHost .ab-grid .ab-tile:not(.locked)[data-id="accessories/glasses"]')
    page.click('#builderHost .ab-tabs button:text-is("Colours")')
    page.click('#builderHost .ab-swatches .sw[aria-label="#e4f0ee"]')
    page.wait_for_timeout(400)
    shot(page, '03-signup-avatar', full=True)
    page.click('#builderHost .ab-tabs button:text-is("Head")')
    page.click('#create')
    page.wait_for_selector('#app:not(.hidden)')
    page.wait_for_selector('.reward')
    page.wait_for_timeout(900)
    shot(page, '04-welcome')
    page.click('#mOk')
    page.wait_for_timeout(500)
    dismiss_perms(page)
    assert page.evaluate("document.body.dataset.theme") == 'helper'
    shot(page, '05-helper-home-new', full=True)

    print('3. log in as Raj (helper) and answer a request')
    logout(page)
    login(page, 'raj@demo.my')
    shot(page, '06-helper-home', full=True)
    page.click('.req[data-req="q_lift_pasarseni"]')
    page.wait_for_selector('#btnAnswer')
    shot(page, '07-request-detail')
    page.click('#btnAnswer')
    page.wait_for_selector('.verdicts')
    page.click('.verdicts button.yes')
    page.fill('#aNote', 'Lift is working — rode it just now. Button panel at wheelchair height.')
    page.click('#samples img[data-s="lift-working"]')
    page.wait_for_timeout(400)
    assert '+45' in page.inner_text('#earnNum')
    shot(page, '08-answer-form')
    page.click('#mSend')
    page.wait_for_selector('.reward .pts')
    page.wait_for_timeout(1100)
    txt = page.inner_text('.reward')
    assert '+' in txt and 'Answer' in txt, txt
    shot(page, '09-reward')
    page.click('#mOk')
    page.wait_for_timeout(400)
    pts = int(page.inner_text('#ptsValue'))
    assert pts > 2450, pts
    page.click('.nav[data-route="requests"]')
    page.wait_for_selector('.req-list')
    page.wait_for_timeout(400)
    shot(page, '10-requests-board')
    page.click('.nav[data-route="community"]')
    page.wait_for_selector('.lb li')
    page.wait_for_timeout(400)
    shot(page, '11-community', full=True)
    page.click('.nav[data-route="profile"]')
    page.wait_for_selector('.badges')
    page.wait_for_timeout(700)
    shot(page, '12-profile', full=True)

    print('4. log in as Aisha (OKU): see the answer, thank, ask a new question')
    logout(page)
    login(page, 'aisha@demo.my')
    assert page.evaluate("document.body.dataset.theme") == 'oku'
    shot(page, '13-oku-home', full=True)
    page.click('#notifBtn')
    page.wait_for_selector('.notif')
    shot(page, '14-oku-notifications')
    page.click('#notifBtn')
    page.click('.req[data-req="q_lift_pasarseni"]')
    page.wait_for_selector('[data-thank]')
    shot(page, '15-oku-answer-received')
    page.click('[data-thank]')
    page.wait_for_selector('.chip:has-text("Thanked")')
    page.wait_for_timeout(400)
    page.click('#modalClose')
    page.click('.nav[data-route="ask"]')
    page.wait_for_selector('#askSend')
    page.click('#quick button[data-n="Nu Sentral"]')
    page.click('[data-tpl="tpl_toilet"]')
    page.fill('#askQ', 'Is the accessible toilet on Level 2 open today? Heading there at 4 pm.')
    shot(page, '16-oku-ask')
    page.click('#askSend')
    page.wait_for_selector('.sent-anim')
    page.wait_for_timeout(900)
    shot(page, '17-oku-ask-sent')
    page.click('#mOk')
    page.wait_for_selector('.hero')
    page.wait_for_timeout(500)
    assert 'Nu Sentral' in page.inner_text('#myReqs')

    print('5. map tab (OKU, wheelchair demo trip)')
    page.click('#demoTrip')
    page.wait_for_selector('.route-opt', timeout=20000)
    page.wait_for_timeout(1500)
    shot(page, '18-map-route')

    print('6. Bahasa Melayu + large text')
    page.click('.nav[data-route="home"]')
    page.wait_for_selector('.hero')
    page.click('#langBtn')
    page.wait_for_timeout(900)
    assert 'Tanya komuniti' in page.inner_text('#view')
    shot(page, '19-oku-home-bm', full=True)
    page.click('#langBtn')
    page.wait_for_timeout(600)

    print('7. mobile viewport')
    m = browser.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    mp = m.new_page()
    mp.on('pageerror', lambda e: errors.append('mobile: ' + str(e)))
    mp.goto(BASE + '/')
    mp.wait_for_selector('.role-cards')
    mp.wait_for_timeout(500)
    shot(mp, '20-mobile-landing', full=True)
    mp.click('.acct[data-email="mei@demo.my"]')
    mp.wait_for_selector('.hero')
    mp.wait_for_timeout(700)
    dismiss_perms(mp)
    shot(mp, '21-mobile-helper-home')
    mp.click('.bottomnav .nav[data-route="requests"]')
    mp.wait_for_selector('.req')
    mp.wait_for_timeout(400)
    shot(mp, '22-mobile-requests')
    mp.click('.req >> nth=0')
    mp.wait_for_selector('.qcard')
    mp.wait_for_timeout(300)
    shot(mp, '23-mobile-request')
    m.close()

    page.request.post(BASE + '/api/demo/reset')
    browser.close()

real_errors = [e for e in errors if 'favicon' not in e and 'tile.openstreetmap' not in e and 'net::ERR' not in e]
print(f'\n{len(shots)} screenshots, {len(real_errors)} console errors')
for e in real_errors: print('  ✗', e)
sys.exit(1 if real_errors else 0)
